### ISSUE TITLE
VueJS Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#11]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by ShawnClake** [comment]
Observations:
* Mid sized learning curve requiring at least 20 hours of exploration before becoming even somewhat knowledgeable in what's possible with vue. 
* Once becoming proficient, Vue is proving to be a valuable resource. 
* Vue really shines when its combined with other libraries such as vue-router, bootstrap, axios, etc.
* Vue components are tricky to wrap a head around (especially with regards to the javascript included within them), however they appear to be extremely useful
* More investigation required

**Comment by herasymj** [comment]
Observations:
Vue has very good documentation not only just for Vue but Vuex, Vue Router, etc.. Although there is a lot to it and the syntax can take a second to wrap your head around, once you understand the basics its easier to pick up. It is also very nice to include conditional rendering directly from the tags.

Learning Curve: 5/10

Usefulness: 10/10

Recommendations: For never using React or Vue before, I found Vue easier to understand and had more clear documentation. As Tristan has previously mentioned, Vue is the way to go.
