### ISSUE TITLE
GulpJS Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#15]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by TristanHeisler** [comment]
Observations:
- A tool for automating repetitive tasks. This includes tasks not necessarily related to dependencies between files, such as image compression. 
- A ton of plugins are already available for use
- No real tutorial on the official page, but I found a great one at https://www.sitepoint.com/introduction-gulp-js/
- I am not yet entirely sure on the overlap between Gulp and Webpack

Learning Curve: 4/10
- It's as easy as determining what tasks to automate and if such functionality already exists within a plugin or not. You can make your own plugins as well.

Usefulness: 8/10

Recommendations:  I definitely think this tool is worth exploring further. If used right, it can save a lot of time as our project grows.
