### ISSUE TITLE
Cordova Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#16]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by TristanHeisler** [comment]
Observations:
- Useful for mobile-based development
- Allows emulation on different mobile devices
- Allows better usage of device-specific capability such  as battery life and camera

Learning Curve: 5/10
- It was easy to get a webpage up and running and test it with an Android emulator
- There does not appear to be a detailed (official) tutorial other than simply getting a basic app up and running
- Templates are available for reuse

Usefulness: 3?/10
- At this time, I don't really see much of a need for this. Our primary focus is a web browser, and we can style the application differently for mobile with relative ease using Bootstrap.

Recommendations: 
I am leaning more towards just using bootstrap.
