### ISSUE TITLE
jOOQ Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#17]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by ShawnClake** [comment]
7/10 - Learning curve (Low is better)
7/10 - Usefulness (High is better)
Recommendation:
Extremely high learning curve, but it appears that the technology is useful for providing a modern interface to MySQL databases. 

Jen's recommendation will be more useful at determining the effectiveness of this technology.

**Comment by herasymj** [comment]
5/10 - Learning curve 

10/10 - Usefulness

Recommendation: I will be using this, as the syntax is very similar to Linq and you can do quite a bit with jOOQ. There is also an extensive manual on how to use the language and lots of documentation.
