### ISSUE TITLE
Simple Java Mail Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#20]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by herasymj** [comment]
3/10 - Learning Curve
10/10 - Usefulness

Recommendation:
If we are sending emails for the application this will be very useful. We have used it before in a lab so we have an idea how it works, plus there are many online tutorials that show you how to use it. As well there seems to be no other well-known technologies to do this.

**Comment by ShawnClake** [comment]
woops, didnt mean to make all those pipeline changes :)
