### ISSUE TITLE
Webpack evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#24]

**Comment by TristanHeisler** [comment]
Observations:
- The official documentation for webpack is very thorough and helpful.
- Looks intimidating at first, but seems like it becomes much simpler with practice.
- Will reduce headaches as our project grows in size and dependencies increase.

Learning Curve: 4/10
- Not as bad as I initially thought it may be, the documentation is great.

Usefulness: 9/10
- Once the configuration file is made and the appropriate dependencies are defined, it is very easy to maintain and use.

Recommendations: I definitely think we should use some type of module bundling tool. From what I have observed so far online, webpack appears to be one of the most robust options.
