### ISSUE TITLE
Develop a formal table/spreadsheet/list of stored/tracked data and the security measures taken

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#44]
This can be a running list as we go, but get some boilerplate down and a place where we can quickly add/remove/edit the list. Ideally, there should be some form of version control and tracking who changed it

**Comment by herasymj** [comment]
Created a basic spreadsheet of data we will be storing, however will probably change as I design the DB.

Lists basic security precautions to take for certain values, as well as categorizes the data (not into tables yet, just grouped so its simple to find).

Will also make some spreadsheets for the tables themselves (per server) along with UMLs.

Stored in Assets -> Database
