### ISSUE TITLE
Develop high level UML diagrams 

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#45]
These diagrams should be for the following components of the architecture:
* Database (Show the relational concepts) - **Jen**
* Authentication - **Shawn**
* Core - **Shawn**
* Assets - **Shawn**
* Middleware - **Shawn**
* Frontend Javascript - Assuming the use of Typescript or similar - **Tristan**

Avoid going into too much detail, we just want to know which classes exist and how they relate, not what methods they'll have.

**Comment by ShawnClake** [comment]
To clarify a little further - This can be as high level as what are the main files you're going to use and how to files relate to each other. 

This exercise is to identify the major components we will need and how they will relate to each other.

**Comment by herasymj** [comment]
Created spreadsheets for both the Auth and Data server to show tables and columns (will also add Views and Stored Procedures to this spreadsheet as they come up), made a basic ERD for each as well. These will need to be iterated through a few times but this should be a decent place to start.
